// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"1024","screenHeight":"576","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"YEP_MessageCore","status":true,"description":"メッセージの表示方法や機能をカスタマイズすることができます。","parameters":{"---一般---":"","Default Rows":"4","Default Width":"Graphics.boxWidth-20","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","Description Wrap":"false","---フォント---":"","Font Name":"GameFont","Font Size":"38","Font Size Change":"6","Font Changed Max":"96","Font Changed Min":"20","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"ALT_WindowTextMove","status":true,"description":"メッセージテキストの位置を調整","parameters":{"zahyou_X":"58","zahyou_Y":"34"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"グリッドサイズ":"48","テストマップID":"-1"}},
{"name":"GALV_VisualNovelChoices","status":true,"description":"(v.1.6) Changes how the \"Choice\" message boxes display to appear more like visual novels.","parameters":{"Command Width":"800","Command Height":"72","Always Middle":"true","Message Gap":"20","Disabled Button":"3"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"NobleMushroom","status":false,"description":"ビジュアルノベルプラグイン","parameters":{"表示タイプ初期値":"0","タイトル表示タイプ":"0","コマンド単位ウェイト":"ON","表示速度変数":"1","表示速度初期値":"1","クリック瞬間表示":"ON","自動改行":"OFF","相対フォントサイズ":"6","明朝体表示":"OFF","ゴシック体表示":"OFF","選択肢接頭辞":"0","画面横サイズ":"0","画面縦サイズ":"0","モバイル画面横サイズ":"0","モバイル画面縦サイズ":"0","モバイルモード":"OFF"}},
{"name":"SimpleVoice","status":true,"description":"簡易ボイスプラグイン","parameters":{"フォルダ名":"voice","オプション名称":"VOICE 音量","オプション初期値":"100"}},
{"name":"OggOnly","status":true,"description":"音声ファイルの再生にoggファイルのみを使用します。","parameters":{"deleteM4a":"false"}},
{"name":"TextDecoration","status":true,"description":"ウィンドウテキストの装飾方法を変更します。","parameters":{"Mode":"0","Red":"0","Green":"0","Blue":"0","Alpha":"0"}},
{"name":"MessageSpeedCustomize","status":true,"description":"メッセージ速度調整プラグイン","parameters":{"表示速度変数":"1","瞬間表示":"false"}},
{"name":"MPP_Patch","status":true,"description":"【2018/12/22】不具合修正プラグイン","parameters":{"Patch1 enabled?":"true","Patch2 enabled?":"true","Patch3 enabled?":"true","Patch4 enabled?":"true","Patch5 enabled?":"true","Patch6 enabled?":"true","Patch7 enabled?":"true","Patch8 enabled?":"true","Patch9 enabled?":"true","Patch10 enabled?":"true","Patch11 enabled?":"true","Patch12 enabled?":"true","Patch13 enabled?":"true","Patch14 enabled?":"true","Patch15 enabled?":"true","Patch16 enabled?":"false"}},
{"name":"CustomizeConfigItem","status":true,"description":"オプション任意項目作成プラグイン","parameters":{"スイッチ項目1":"","数値項目1":"メッセージスピード:2:1:OFF:0:2:1:","音量項目1":"","文字項目1":"時期:0:3:OFF:バレンタイン, クリスマス:script","スイッチ項目2":"","数値項目2":"","音量項目2":"","文字項目2":""}},
{"name":"PictureVariableSetting","status":true,"description":"ピクチャ関連のイベント機能拡張プラグイン","parameters":{"初期値":"OFF","ピクチャ表示最大数":""}},
{"name":"AutoLoad","status":false,"description":"タイトル画面仕様変更プラグイン","parameters":{"効果音演奏":"ON","完全スキップ":"OFF","タイトルマップID":"2"}},
{"name":"AnotherNewGame","status":true,"description":"アナザーニューゲーム追加プラグイン","parameters":{"name":"エクストラ","map_id":"2","map_x":"1","map_y":"1","hidden":"OFF","disable":"OFF","file_load":"OFF","no_fadeout":"ON","manage_number":"","add_position":"0"}},
{"name":"ChangeWindowTouchPolicy","status":true,"description":"ウィンドウタッチ仕様変更プラグイン","parameters":{"枠外タッチ動作":"キャンセル"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"ON","ピクチャ番号の変数番号":"300","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"OFF","戦闘中常にコモン実行":"OFF"}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"-253","Offset Y":"55","Width":"300","Background":"2"}},
{"name":"UTA_CommonSave","status":true,"description":"共有のセーブデータを作成し、指定したスイッチ・変数の状態をセーブデータ間で共有します。","parameters":{"Target Switches":"10-18","Target Variables":"","Is Auto":"true","Auto on Gameover":"false","Show Trace":"false"}},
{"name":"MasterVolumeOption","status":true,"description":"マスターボリューム設定プラグイン","parameters":{"項目名称":"全体 音量","初期値":"70","音量の増減量":"10"}}
];
